import dns from "node:dns";
dns.setServers(['8.8.8.8', '8.8.4.4']);
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import FableNavbar from "@/components/FableNavbar";
import FableFooter from "@/components/FableFooter";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col" cz-shortcut-listen="true">
        <FableNavbar></FableNavbar>
        <main>
          {children}
        </main>
        <ToastContainer />
        <FableFooter></FableFooter>
        </body>
    </html>
  );
}
